import { ThemeConfig, ThemeId } from '../types';

export const READING_THEMES: Record<ThemeId, ThemeConfig> = {
  classic: {
    id: 'classic',
    name: 'Classic',
    description: 'Warm white paper with deep charcoal typography',
    paperColor: '#FAF8F5',
    textColor: '#252525',
    accentColor: '#6F8068',
    isDark: false,
  },
  ivory: {
    id: 'ivory',
    name: 'Ivory',
    description: 'Soft cream paper with gentle contrast',
    paperColor: '#FFFDF9',
    textColor: '#2C2825',
    accentColor: '#7A896F',
    isDark: false,
  },
  sepia: {
    id: 'sepia',
    name: 'Sepia',
    description: 'Warm antique yellow and brown tones',
    paperColor: '#F7EFE0',
    textColor: '#433422',
    accentColor: '#8C6D46',
    isDark: false,
  },
  parchment: {
    id: 'parchment',
    name: 'Parchment',
    description: 'Textured fibrous aged paper feel',
    paperColor: '#F5EEDB',
    textColor: '#383025',
    accentColor: '#6E7E64',
    isDark: false,
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    description: 'Deep charcoal green-black with warm ivory text',
    paperColor: '#1B1E19',
    textColor: '#E8E3D7',
    accentColor: '#8E9F87',
    isDark: true,
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    description: 'Deep muted moss green reading atmosphere',
    paperColor: '#1E281F',
    textColor: '#E0E7DC',
    accentColor: '#9FB895',
    isDark: true,
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Pure neutral reading surface with zero grain',
    paperColor: '#FFFFFF',
    textColor: '#111827',
    accentColor: '#4B5563',
    isDark: false,
  },
};
